### ISSUE TITLE
Rewrite and host it on vercel

### ISSUE THREAD

**Issue by lorypelli** [drHyperion451/does-uBO-bypass-yt#43]
You should host the project on vercel, also you said that you aren't a good web dev, the suggestion is: rewrite this by making it server side and not client side (I saw by your account that you have other projects in PYTHON or RUST, so I think doing an api won't be difficult to you

**Comment by lorypelli** [comment]
Actually, if you want to host it on vercel, you need to use serverless function provided by them, try using vite as package bundler (will optize website spit by optimizing code)

**Comment by lorypelli** [comment]
Not sure anymore if it's a good idea, tell me what you think

**Comment by lorypelli** [comment]
If I have time, can I do a PR?

**Comment by lorypelli** [comment]
Frameworks I recommend are astro or svelte

**Comment by drHyperion451** [comment]
Hello, thanks for making this proporsal but honestly I don't think this is a good idea: 

1. Doing a full rewrite using a framework is not going to give any more features than it has.
2. Vanilla JS uses less resources, meaning lightweight code and incredibly compatible code that works very quick. 
3. Vanilla JS requires less time to set up and manage for incredibly simple projects like this. This website has zero dependencies and external libraries and it's very easy to code.
4. Knowledge. I've never used a js framework enough to create a project that will be outside the "chill hobby area" and actually serve as a good tool. Also never used Verge.
5. Verge is very interesting and I will look into that for future projects, but if all previous points applies, why exactly?. Github pages is incredibly easy and quick to deploy. No intermediates or anything.
6. Hosting a server for this and doing the fetch in a server will increment speed for sure but at the price of creating a backend, maintaining the server, using two services instead of just GitHub... just for 1-2 seconds of fetching YouTube.
7. Expanding more point 6 using a server can be blocked by YouTube (because they can `ping` my website and block any request from an specific ip). I don't think they even care about this stupid website enough but better no leave any potential vulnerabilities on.
8. Changing the server will change the URL, so this GitHub project needs to be structually different to have another index.html that will redirect to the correct website, making a bit harder to transfer.

These are some reasons why I did this in plain JS instead of using a Framework back a month ago when I started the project. This could change though if the project needs to, but this version is very close to be the definitive. Simpler is usually better, and Frameworks sometimes are unnecesary complex for very small projects. I will look into your recommendations though
